### ISSUE TITLE
您好，关于MIT Licence，我有一些问题想向您请教

### ISSUE THREAD

**Issue by kinson-liu** [qyxxjd/License#1]
您好，最近看了网上浏览MIT，发现网上只是介绍了几种开源协议，并没有详细地说明。请问，如果我发布了基于MIT Licence 的项目，那我可以用其他证书发布吗？我需要在README.md里声明吗？谢谢！

**Comment by qyxxjd** [comment]
- 根据自己的项目，选择合适的开源协议
- 参考一下 [Glide](https://github.com/bumptech/glide) 声明的开源协议就有多个
- `README.md`里需要声明开源协议

License
-------
BSD, part MIT and Apache 2.0. See the [LICENSE]() file for details.

**Comment by kinson-liu** [comment]
嗯嗯，get到了，❤十分感谢！他把第三方的Licence在自己的Licence中重新声明下，原第三方的Licence仍在。
